# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
  preBuild: []
  postBuild: []

jobs:
- job:
  displayName: 'Android Build Project'
  steps:
    - ${{ parameters.preBuild }} # Here we start the prebuild steps

    - task: Bash@3
      displayName: 'BUILD_BASE_1'
      inputs:
        targetType: 'inline'
        script: |
          echo 1

    - task: Bash@3
      displayName: 'BUILD_BASE_4'
      inputs:
        targetType: 'inline'
        script: |
          pwd

    - task: Bash@3
      displayName: 'BUILD_BASE_3'
      inputs:
        targetType: 'inline'
        script: |
          echo "test" >> test.txt

    - task: Bash@3
      displayName: 'BUILD_BASE_4'
      inputs:
        targetType: 'inline'
        script: |
          echo 4

    - ${{ parameters.postBuild }} # Here we start the postbuild steps