# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  - name: msgTextNew
    value: asd123asd

resources:
  repositories:
  - repository: ExtRepo # The name used to reference this repository in the checkout step
    type: github
    endpoint: LyubomirStoimchev
    name: LyubomirStoimchev/my-app
    
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, $(msgTextNew), $(testVariable)!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: echo "##vso[group] Check out of external repo."
- checkout: ExtRepo
- script: echo "##vso[endgroup]"
