parameters:
  # - name: preBuildSteps
  #   type: stepList
  #   default: []
  # - name: postBuildSteps
  #   type: stepList
  #   default: []
  preBuild: []
  postBuild: []
  DependsOn: {}
  # - name: AppRepository
  #   type: object
  #   default: {}

jobs:
- job: UploadApplicationJob
  displayName: 'UploadApplicationJob'
  # ${{ if parameters.DependsOn }}:
  #   dependsOn: '${{ parameters.DependsOn }}'
  steps:
    - ${{ parameters.preBuild }} # Here we start the prebuild steps

    - task: Bash@3
      displayName: 'Upload 1'
      inputs:
        targetType: 'inline'
        script: |
          pwd
          mkdir downloaded2

    - task: DownloadPipelineArtifact@2
      inputs:
        artifact: drop
        path: $(System.DefaultWorkingDirectory)/downloaded2 # Required 

    - task: Bash@3
      displayName: 'Upload 2'
      inputs:
        targetType: 'inline'
        script: |
          ls -la -R
          cat $(System.DefaultWorkingDirectory)/downloaded2/test.txt

    - ${{ parameters.postBuild }} # Here we start the postbuild steps