trigger:
- main

pool:
  vmImage: ubuntu-latest
resources:
  repositories:
  - repository: NativeAppRepo
    type: bitbucket
    endpoint: TestConnectionBB
    name: draftkingsdevelopers/dk-gaming-app
    ref: develop

stages:
  - stage: ApplicationPreparation
    jobs:
    - job: GenericBuild
      steps:
      - checkout: NativeAppRepo
      - template: android-build-template.yml
        parameters:
          preBuild:
            - task: Bash@3
              displayName: 'PRE_BUILD_1'
              inputs:
                targetType: 'inline'
                script: |
                  echo 1
            - task: Bash@3
              displayName: 'PRE_BUILD_2'
              inputs:
                targetType: 'inline'
                script: |
                  echo 2
          postBuild:
            - task: Bash@3
              displayName: 'POST_BUILD_1'
              inputs:
                targetType: 'inline'
                script: |
                  echo 3

    - job: GenericArchive
      dependsOn: GenericBuild
      steps:
      - template: android-archive-template.yml
        parameters:
          #DependsOn: AndroidBuildProject
          preBuild:
            - task: Bash@3
              displayName: 'PRE_UPLOAD_1'
              inputs:
                targetType: 'inline'
                script: |
                  echo 1
            - task: Bash@3
              displayName: 'PRE_UPLOAD_2'
              inputs:
                targetType: 'inline'
                script: |
                  echo 2
          postBuild:
            - task: Bash@3
              displayName: 'POST_UPLOAD_1'
              inputs:
                targetType: 'inline'
                script: |
                  echo 3

    - job: GenericUpload
      dependsOn: GenericArchive
      steps:
      - template: browser-stack-upload.yml
        # dependsOn: AndroidArchiveProject
        parameters:
          #DependsOn: AndroidArchiveProject
          preBuild:
            - task: Bash@3
              displayName: 'PRE_UPLOAD_1'
              inputs:
                targetType: 'inline'
                script: |
                  echo 1
            - task: Bash@3
              displayName: 'PRE_UPLOAD_2'
              inputs:
                targetType: 'inline'
                script: |
                  echo 2
          postBuild:
            - task: Bash@3
              displayName: 'POST_UPLOAD_1'
              inputs:
                targetType: 'inline'
                script: |